-- Create impersonation_sessions table
CREATE TABLE IF NOT EXISTS public.impersonation_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL REFERENCES public.admin(id),
    target_user_id INTEGER NOT NULL,
    target_role VARCHAR(20) NOT NULL CHECK (target_role IN ('siswa', 'panitia')),
    started_at TIMESTAMPTZ DEFAULT NOW(),
    ended_at TIMESTAMPTZ,
    active BOOLEAN DEFAULT TRUE
);

-- Create audit_logs table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL REFERENCES public.admin(id),
    target_user_id INTEGER,
    action TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) if needed (optional but recommended)
ALTER TABLE public.impersonation_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
